# Generated by Django 4.1 on 2022-08-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(max_length=255)),
                ('biling_address', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
